[build-system]
requires = ["setuptools", "setuptools-scm"]
build-backend = "setuptools.build_meta"

[tool.setuptools.packages.find]
where = ["src"]  # list of folders that contain the packages (["."] by default)

[project]
name = "vietlott-data"
version = "0.1.1"
description = ""
authors = [
    { name = "Viet Vu", email = "vietvudanh@gmail.com" },
]
dependencies = [
    "bs4>=0.0.1",
    "pandas>=2.1.0",
    "lxml>=4.9.3",
    "attrs>=23.1.0",
    "cattrs>=23.1.2",
    "click>=8.1.7",
    "pendulum>=2.1.2",
    "requests>=2.31.0",
    "tabulate>=0.9.0",
    "httpx>=0.24.1",
    "loguru>=0.7.0",
]
requires-python = ">=3.11"
readme = "README.md"
license = { text = "MIT" }


[project.optional-dependencies]
dev = [
    "pytest>=7.4.0",
]

[project.scripts]
vietlott-crawl = "vietlott.cli.crawl:crawl"
vietlott-missing = "vietlott.cli.crawl:detect_missing_data"

[tool.ruff]
line-length = 120
